SELECT * FROM OAUTH2_AUTHORIZATION ;
SELECT * FROM OAUTH2_AUTHORIZATION_CONSENT ;
SELECT * FROM OAUTH2_REGISTERED_CLIENT ;
SELECT * FROM ROLES ;
SELECT * FROM USERS ;
SELECT * FROM USERS_ROLES ;
SELECT * FROM OAUTH2_JWK ;